logging:
  level:
    com.smartcode: info

spring:
  datasource:
    url: jdbc:mysql://172.21.16.16:3306/pet?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: csdiao210!
  redis:
    host: 172.21.16.12
    port: 6379
    password: csdiao210

easy-es:
  address: 101.42.149.252:9200
  username:
  password: