logging:
  level:
    com.smartcode: debug


spring:
  datasource:
    url: jdbc:mysql://bj-cynosdbmysql-grp-r787tg6s.sql.tencentcdb.com:25979/pet?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: csdiao210!
  redis:
    host: 127.0.0.1
    port: 6379
    password:

easy-es:
  address: 127.0.0.1:9200
  username:
  password:

swagger:
  try-host: http://localhost:${server.port}